# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: peer_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'peer_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12peer_service.proto\x12\x03p2p\"<\n\x0fRegisterRequest\x12\x0f\n\x07peer_id\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\"4\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x1e\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\"#\n\x0eSearchResponse\x12\x11\n\tfile_urls\x18\x01 \x03(\t\"$\n\x0f\x44ownloadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"$\n\x0c\x46ileResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"8\n\rUploadRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x14\n\x0c\x66ile_content\x18\x02 \x01(\x0c\"2\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf1\x01\n\x0bPeerService\x12;\n\x0cRegisterPeer\x12\x14.p2p.RegisterRequest\x1a\x15.p2p.RegisterResponse\x12\x35\n\nSearchFile\x12\x12.p2p.SearchRequest\x1a\x13.p2p.SearchResponse\x12\x37\n\x0c\x44ownloadFile\x12\x14.p2p.DownloadRequest\x1a\x11.p2p.FileResponse\x12\x35\n\nUploadFile\x12\x12.p2p.UploadRequest\x1a\x13.p2p.UploadResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'peer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=27
  _globals['_REGISTERREQUEST']._serialized_end=87
  _globals['_REGISTERRESPONSE']._serialized_start=89
  _globals['_REGISTERRESPONSE']._serialized_end=141
  _globals['_SEARCHREQUEST']._serialized_start=143
  _globals['_SEARCHREQUEST']._serialized_end=173
  _globals['_SEARCHRESPONSE']._serialized_start=175
  _globals['_SEARCHRESPONSE']._serialized_end=210
  _globals['_DOWNLOADREQUEST']._serialized_start=212
  _globals['_DOWNLOADREQUEST']._serialized_end=248
  _globals['_FILERESPONSE']._serialized_start=250
  _globals['_FILERESPONSE']._serialized_end=286
  _globals['_UPLOADREQUEST']._serialized_start=288
  _globals['_UPLOADREQUEST']._serialized_end=344
  _globals['_UPLOADRESPONSE']._serialized_start=346
  _globals['_UPLOADRESPONSE']._serialized_end=396
  _globals['_PEERSERVICE']._serialized_start=399
  _globals['_PEERSERVICE']._serialized_end=640
# @@protoc_insertion_point(module_scope)
